# CodeRabbit Configuration
# Docs: https://docs.coderabbit.ai/reference/configuration

language: "en-US"
early_access: false
enable_free_tier: false

reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false  # Skip reviews for draft PRs
  
  # Ignore patterns - tell CodeRabbit to skip certain checks
  path_filters:
    - "!**/*.md"  # We handle markdown linting separately
    - "!docs/**"  # Design docs are already reviewed
  
  # Custom instructions for the reviewer
  # Path-based instructions for specific file types
  path_instructions:
    - path: "src/**/*.ts"
      instructions: |
        Logic errors, correctness bugs, edge cases in GitHub API integration.
        Error handling: unhandled promise rejections, missing try-catch, incorrect error propagation.
        Security: token exposure, injection risks, unauthorized access.
        Performance: unnecessary API calls, inefficient parsing, memory leaks.
        Async/await correctness with Octokit and MCP protocol handling.
        Type safety issues that TypeScript strict mode might miss.
        MCP protocol compliance and stdio transport correctness.
        Pagination logic correctness and edge cases.
        GitHub API rate limiting and retry logic.
        User preference precedence (explicit > preference > default).

chat:
  auto_reply: false

# Tool-specific configuration
tools:
  shellcheck:
    enabled: true
  markdownlint:
    enabled: false  # We run this separately
  languagetool:
    enabled: false  # Grammar checking not needed for code

